"""`reasonhold`: the command-line wrapper over the ReasonHold facade."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from reasonhold.errors import ReasonHoldError
from reasonhold.governance import SOURCE_SUFFIXES
from reasonhold.indexer import EXCLUDED_PATH_PARTS
from reasonhold.project import MANIFEST_NAMES, slug

HUMAN = {"kind": "human"}


def scaffold_manifest(root: Path) -> str:
    project_id = slug(root.name)
    docs = sorted(p.relative_to(root).as_posix() for d in ("docs/architecture", "docs/specs")
                  for p in (root / d).rglob("*.md")) if (root / "docs").is_dir() else []
    guidance = [n for n in ("AGENTS.md", "CLAUDE.md", "README.md") if (root / n).is_file()]
    anchor = (docs or guidance or ["README.md"])[0]
    areas = []
    for d in sorted(p for p in root.iterdir() if p.is_dir()):
        if d.name.startswith(".") or d.name in EXCLUDED_PATH_PARTS or d.name in ("docs", "tests"):
            continue
        suffixes = sorted({f.suffix for f in d.rglob("*") if f.is_file() and f.suffix in SOURCE_SUFFIXES
                           and not any(part in EXCLUDED_PATH_PARTS for part in f.relative_to(root).parts)})
        if suffixes:
            globs = ", ".join(f'"{d.name}/**/*{s}"' for s in suffixes)
            areas.append(f"  {d.name}:\n    description: {d.name}\n    projects: [{d.name}]\n"
                         f"    docs: [{anchor}]\n    index: [{globs}]\n")
    if not areas:
        areas.append(f"  {project_id}:\n    description: {project_id}\n    projects: [{project_id}]\n"
                     f"    docs: [{anchor}]\n    index: [\"*.md\"]\n")
    global_docs = ", ".join(docs) if docs else ""
    index = ", ".join(guidance + (['"docs/**/*.md"'] if (root / "docs").is_dir() else []))
    return (
        "# Generated by `reasonhold init`. Placement is declared, never inferred:\n"
        "# review every list, then run `reasonhold check` and `reasonhold coverage`.\n"
        f"project:\n  id: {project_id}\n  decisions: decisions.jsonl\n"
        f"global:\n  docs: [{global_docs}]\n  index: [{index}]\n"
        "areas:\n" + "".join(areas)
    )


def _parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="reasonhold", description="What a coding agent should believe about this repository.")
    p.add_argument("--root", type=Path, default=None, help="repository root (default: current directory)")
    p.add_argument("--json", action="store_true", help="print JSON")
    sub = p.add_subparsers(dest="command", required=True)

    init = sub.add_parser("init", help="scaffold reasonhold.yaml from the detected layout")
    init.add_argument("--force", action="store_true")
    sub.add_parser("check", help="validate the manifest, decision log and pending sidecar")
    idx = sub.add_parser("index", help="index this branch (incremental; full when the rules require it)")
    idx.add_argument("--full", action="store_true")
    idx.add_argument("--dry-run", action="store_true")
    idx.add_argument("--area", action="append", default=[])
    cur = sub.add_parser("curate", help="mechanical manifest curation from git renames and deletions")
    cur.add_argument("--dry-run", action="store_true")
    sub.add_parser("freshness")
    sub.add_parser("inventory")
    gc = sub.add_parser("gc", help="drop this project's collections for deleted branches")
    gc.add_argument("--yes", action="store_true")
    s = sub.add_parser("search")
    s.add_argument("query")
    s.add_argument("--top-k", type=int, default=5)
    g = sub.add_parser("govern", help="documents governing a path")
    g.add_argument("path")
    d = sub.add_parser("decisions")
    dsub = d.add_subparsers(dest="action", required=True)
    ds = dsub.add_parser("search")
    ds.add_argument("query")
    ds.add_argument("--top-k", type=int, default=5)
    ds.add_argument("--status", default="active", choices=["active", "superseded", "all"])
    dshow = dsub.add_parser("show")
    dshow.add_argument("id")
    dsub.add_parser("audit", help="decisions that read like retractions but record none")
    c = sub.add_parser("conflicts")
    c.add_argument("--path")
    c.add_argument("--all", action="store_true")
    sy = sub.add_parser("symbols")
    sy.add_argument("chunk_type")
    sy.add_argument("--prefix")
    sy.add_argument("--names", action="store_true")
    sub.add_parser("coverage")
    dec = sub.add_parser("decide", help="record a decision")
    dec.add_argument("--stdin", action="store_true", help="read the decision as a JSON object on stdin")
    dec.add_argument("--topic")
    dec.add_argument("--decision")
    dec.add_argument("--rationale")
    dec.add_argument("--alternative", action="append", default=[])
    dec.add_argument("--context", default="")
    dec.add_argument("--tag", action="append", default=[])
    dec.add_argument("--supersede", action="append", default=[], metavar="PATH[#SECTION]=SUMMARY")
    dec.add_argument("--supersedes-record", action="append", default=[], metavar="DEC_ID")
    dec.add_argument("--resolves", action="append", default=[], metavar="PEN_ID")
    dec.add_argument("--actor")
    cand = sub.add_parser("candidates")
    csub = cand.add_subparsers(dest="action")
    csub.add_parser("list")
    cp = csub.add_parser("promote")
    cp.add_argument("id")
    cr = csub.add_parser("reject")
    cr.add_argument("id")
    cr.add_argument("--note")
    pre = sub.add_parser("preamble")
    pre.add_argument("--format", choices=["text", "claude-hook"], default="text")
    sub.add_parser("mcp", help="run the stdio MCP server")
    return p


def _decide_kwargs(args) -> dict:
    if args.stdin:
        data = json.load(sys.stdin)
        if not isinstance(data, dict):
            raise ValueError("--stdin expects one JSON object")
        data.setdefault("provenance", dict(HUMAN))
        return data
    supersedes = []
    for item in args.supersede:
        path, sep, summary = item.partition("=")
        if not sep:
            raise ValueError(f"--supersede {item!r}: expected PATH[#SECTION]=SUMMARY")
        supersedes.append({"path": path, "retraction_summary": summary})
    provenance = dict(HUMAN, **({"actor": args.actor} if args.actor else {}))
    return {
        "topic": args.topic, "decision": args.decision, "rationale": args.rationale,
        "alternatives_considered": args.alternative, "session_context": args.context, "tags": args.tag,
        "supersedes": supersedes, "supersedes_records": args.supersedes_record,
        "resolves": args.resolves or None, "provenance": provenance,
    }


def _progress(*a) -> None:
    print(*a, file=sys.stderr)


def _print(value, as_json: bool) -> None:
    if as_json:
        print(json.dumps(value, indent=2, sort_keys=True, default=str))
    elif isinstance(value, str):
        print(value, end="" if value.endswith("\n") else "\n")
    else:
        print(json.dumps(value, indent=2, sort_keys=True, default=str))


def main(argv=None, *, factory=None) -> int:
    args = _parser().parse_args(argv)
    root = (args.root or Path.cwd()).resolve()

    if args.command == "preamble":
        from reasonhold.preamble import claude_hook_json, render_preamble

        text = render_preamble(root)
        print(claude_hook_json(text) if args.format == "claude-hook" else text, end="" if args.format == "text" else "\n")
        return 0
    if args.command == "mcp":
        from reasonhold.mcp_server import serve

        serve(root)
        return 0

    try:
        if args.command == "init":
            if any((root / n).exists() for n in MANIFEST_NAMES) and not args.force:
                print("reasonhold: a manifest already exists here (use --force to overwrite)", file=sys.stderr)
                return 2
            (root / "reasonhold.yaml").write_text(scaffold_manifest(root))
            (root / "decisions.jsonl").touch()
            print("wrote reasonhold.yaml and decisions.jsonl; review the manifest, then run `reasonhold check`")
            return 0
        from reasonhold.api import ReasonHold

        rh = (factory or ReasonHold)(root)
        try:
            return _dispatch(rh, args)
        finally:
            rh.close()
    except (ReasonHoldError, ValueError) as exc:
        print(f"reasonhold: {exc}", file=sys.stderr)
        return 2


def _dispatch(rh, args) -> int:
    j = args.json
    cmd = args.command
    if cmd == "check":
        problems = rh.check()
        _print(problems if j else "\n".join(
            f"{p['severity']}: {p['file']}{':' + str(p['line']) if p['line'] else ''}: {p['message']}" for p in problems
        ) or "ok", j)
        return 1 if any(p["severity"] == "error" for p in problems) else 0
    if cmd == "index":
        _print(rh.index(full=args.full, dry_run=args.dry_run, areas=args.area, out=_progress), j)
        return 0
    if cmd == "curate":
        _print(rh.curate(dry_run=args.dry_run), j)
        return 0
    if cmd == "freshness":
        result = rh.freshness()
        _print(result if j else result["summary"], j)
        return 0 if result["clean"] else 1
    if cmd == "inventory":
        _print(rh.inventory(), j)
        return 0
    if cmd == "gc":
        _print(rh.gc(yes=args.yes, out=_progress), j)
        return 0
    if cmd == "search":
        _print(rh.search_docs(args.query, args.top_k), j)
        return 0
    if cmd == "govern":
        _print(rh.governing_docs(args.path), j)
        return 0
    if cmd == "decisions":
        if args.action == "search":
            _print(rh.search_decisions(args.query, args.top_k, args.status), j)
        elif args.action == "show":
            _print(rh.decision(args.id), j)
        else:
            from reasonhold.audit import find_candidates, render_report

            print(render_report(find_candidates(rh.project.decisions_path)))
        return 0
    if cmd == "conflicts":
        _print(rh.conflicts(args.path, open_only=not args.all), j)
        return 0
    if cmd == "symbols":
        _print(rh.symbols(args.chunk_type, args.prefix, args.names), j)
        return 0
    if cmd == "coverage":
        result = rh.coverage()
        _print(result, j)
        return 1 if result["holes"] else 0
    if cmd == "decide":
        _print(rh.store_decision(**_decide_kwargs(args)), j)
        return 0
    if cmd == "candidates":
        if args.action == "promote":
            _print(rh.promote(args.id, dict(HUMAN)), j)
        elif args.action == "reject":
            _print(rh.reject(args.id, args.note, dict(HUMAN)), j)
        else:
            rows = rh.candidates()
            _print(rows if j else "\n".join(
                f"{r['id']}  {r['target']} <- {', '.join(r['reads'])}  ({r['reason']})" for r in rows
            ) or "no open candidates", j)
        return 0
    raise ValueError(f"unknown command {cmd}")


if __name__ == "__main__":
    sys.exit(main())
